spring.application.name=customer-profile-service


server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/customer_profile_db
spring.datasource.username=root
spring.datasource.password=navalvyas

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true